INSERT INTO communities (`name`, `members`) VALUES
('Street Photography Collective', 0),
('Nature Lens Club', 0),
('Portrait Pros', 0),
('Urban Explorers', 0),
('Wildlife Watchers', 0),
('Black & White Masters', 0),
('Travel Shutterbugs', 0),
('Minimalist Moments', 0),
('Nightscape Society', 0),
('Macro Magic', 0),
('Film & Vintage Shooters', 0),
('Landscape Legends', 0),
('Creative Compositions', 0),
('Photo Gearheads', 0),
('Newbie Photographers Hub', 0),
('Event & Wedding Shooters', 0),
('Drone Photography Group', 0),
('Food Photography Network', 0),
('Fashion & Editorial Collective', 0),
('Abstract Artistry', 0);
